<?php

namespace AppBundle\Repository\People;

use Doctrine\ORM\EntityRepository;

/**
 * BuddyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuddyRepository extends EntityRepository
{
}
