<?php

namespace AppBundle\Repository\People;

use AppBundle\Entity\People\Person;
use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{

    /**
     * @param Person $person
     * @param int    $resultCount
     *
     * @return Person[]
     */
    public function findRandomWithPerson(Person $person, $resultCount = 1)
    {
        return $this->createQueryBuilder('p')
            ->where('p.id != :personId')
            ->setParameter('personId', $person->getId())
            ->orderBy('RANDOM()')
            ->setMaxResults($resultCount)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int $resultCount
     *
     * @return Person[]
     */
    public function findRandom($resultCount = 1)
    {
        return $this->createQueryBuilder('p')
            ->orderBy('RANDOM()')
            ->setMaxResults($resultCount)
            ->getQuery()
            ->getResult();
    }
}
