<?php

namespace AppBundle\Repository\People;

use AppBundle\Entity\People\PersonImpl;
use BusinessRules\Entities\People\Person;
use BusinessRules\Gateways\People\PersonGateway;
use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository implements PersonGateway
{
    /**
     * @param PersonImpl $person
     * @param int        $resultCount
     *
     * @return PersonImpl[]
     */
    public function findRandomWithPerson(PersonImpl $person, $resultCount = 1)
    {
        return $this->createQueryBuilder('p')
            ->where('p.id != :personId')
            ->setParameter('personId', $person->getId())
            ->orderBy('RANDOM()')
            ->setMaxResults($resultCount)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int $resultCount
     *
     * @return PersonImpl[]
     */
    public function findRandom($resultCount = 1)
    {
        return $this->createQueryBuilder('p')
            ->orderBy('RANDOM()')
            ->setMaxResults($resultCount)
            ->getQuery()
            ->getResult();
    }

    /**
     * {@inheritdoc}
     */
    public function insert(Person $person)
    {
        $this->getEntityManager()->persist($person);
        $this->getEntityManager()->flush();
    }
}
