rm_people_add:
    path:     /add
    defaults: { _controller: AppBundle:People/AddPerson:add }

rm_people_list:
    path:     /list
    defaults: { _controller: AppBundle:People/ListPerson:list }

rm_people_search_buddies:
    path:     /{id}/search-buddies
    defaults: { _controller: AppBundle:People/SearchBuddies:search }
