app_people_create:
    path:     /new
    defaults: { _controller: AppBundle:People/CreatePerson:create }

rm_people_list:
    path:     /list
    defaults: { _controller: AppBundle:People/ListPerson:list }

rm_people_search_buddies:
    path:     /{id}/search-buddies
    defaults: { _controller: AppBundle:People/SearchBuddies:search }
